name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Save Docker image as .tar file
        run: |
          TIMESTAMP=$(date +%s)
          docker save -o tsipderp$TIMESTAMP.tar my-image-name:$TIMESTAMP

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: tsipderp$(date +%s).tar
          path: tsipderp$(date +%s).tar
