name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          TIMESTAMP=$(date +%s)
          docker build . -f Dockerfile -t my-image-name:$TIMESTAMP

      - name: Save Docker image as .tar file
        run: |
          docker save -o tsipderp-$TIMESTAMP.tar my-image-name:$TIMESTAMP

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: tsipderp-$TIMESTAMP.tar
